# Generated by Django 5.1.7 on 2025-04-19 13:12

import django.db.models.deletion
import job_order.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JOB_ORDER_FIRST_PAGE",
            fields=[
                (
                    "job_order_number",
                    models.CharField(
                        max_length=255, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("project", models.CharField(max_length=255)),
                ("sensor", models.CharField(max_length=255)),
                ("enow", models.CharField(max_length=255)),
                ("required_by_date", models.DateField()),
                ("request_provided_by", models.CharField(max_length=255)),
                ("request_authorized_by", models.CharField(max_length=255)),
                ("requirement", models.CharField(max_length=255)),
                ("selected_inputs", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="SWT2",
            fields=[
                (
                    "job_order_number",
                    models.OneToOneField(
                        db_column="job_order_number",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="swt2_job_order_number",
                        serialize=False,
                        to="job_order.job_order_first_page",
                        verbose_name="job_order_number",
                    ),
                ),
                ("package", models.CharField(blank=True, max_length=255, null=True)),
                ("version", models.CharField(blank=True, max_length=255, null=True)),
                ("subsystem", models.CharField(blank=True, max_length=255, null=True)),
                ("availability1", models.BooleanField(default=False)),
                ("sw_req_doc_remarks", models.TextField(blank=True, null=True)),
                ("availability2", models.BooleanField(default=False)),
                ("sw_des_doc_remarks", models.TextField(blank=True, null=True)),
                ("availability3_1", models.BooleanField(default=False)),
                ("src_base_doc_remarks", models.TextField(blank=True, null=True)),
                ("availability3_2", models.BooleanField(default=False)),
                ("src_curr_remarks", models.TextField(blank=True, null=True)),
                ("availability4", models.BooleanField(default=False)),
                ("tc_and_rep_remarks", models.TextField(blank=True, null=True)),
                ("availability5", models.BooleanField(default=False)),
                ("ssrb_or_ssdrc_remarks", models.TextField(blank=True, null=True)),
                ("availability6", models.BooleanField(default=False)),
                ("additional_remarks", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SWT3",
            fields=[
                (
                    "job_order_number",
                    models.OneToOneField(
                        db_column="job_order_number",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="swt3_job_order_number",
                        serialize=False,
                        to="job_order.job_order_first_page",
                        verbose_name="job_order_number",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("nature_of_work", models.TextField(blank=True, null=True)),
                (
                    "availability_of_inputs",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "job_alloted_to",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("date_of_commencement", models.DateField(blank=True, null=True)),
                ("completion_date", models.DateField(blank=True, null=True)),
                (
                    "job_allotted_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "job_authorized_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "received_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("comments", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SWT4",
            fields=[
                (
                    "job_order_number",
                    models.OneToOneField(
                        db_column="job_order_number",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="swt4_job_order_number",
                        serialize=False,
                        to="job_order.job_order_first_page",
                        verbose_name="job_order_number",
                    ),
                ),
                (
                    "t_and_e_engineer",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("rating", models.CharField(blank=True, max_length=255, null=True)),
                ("subsystem", models.CharField(blank=True, max_length=255, null=True)),
                ("signature", models.CharField(blank=True, max_length=255, null=True)),
                ("Remarks", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SWT2Files",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1.sw_req_doc", "1_Software_Requirement_Document"),
                            ("2.sw_des_doc", "2_Software_Design_Document"),
                            (
                                "3_1.src_base_file",
                                "3_1_Source_Code_(Baseline_version)_Files",
                            ),
                            (
                                "3_2.src_curr_file",
                                "3_2_Source_Code_(Current_version)_Files",
                            ),
                            ("4.tc_and_rep_doc", "4_Test_Cases_and_Report_Files"),
                            (
                                "5.ssrb_or_ssdrc_doc",
                                "5_SSDRC/SSRB_Committee_minutes_and_closeouts_Files",
                            ),
                            ("6.additional_doc", "6_Additional_Files"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=job_order.models.SWT2Files.file_upload_path,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True, default="NO File Attached", max_length=50, null=True
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "swt2",
                    models.ForeignKey(
                        db_column="job_order_number",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="job_order.swt2",
                    ),
                ),
            ],
        ),
    ]
